import {test} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {startReleaseServer} from '../src/release-server.js';

const origin='https://release.example';
const verifier='v'.repeat(64),challenge=createHash('sha256').update(verifier).digest('base64url');
const redirect='https://chatgpt.com/connector/oauth/test-only';
const resource=origin+'/mcp';
async function setup(path=':memory:'){const app=startReleaseServer({publicOrigin:origin,port:0,dataPath:path});await once(app.http,'listening');return {app,base:'http://127.0.0.1:'+app.http.address().port};}
async function register(base){const r=await fetch(base+'/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({redirect_uris:[redirect],token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code'],client_name:'Synthetischer OAuth-Test'})});assert.equal(r.status,201);return r.json();}
async function authorization(base,client,name,scopes='loops:read loops:write'){
 const q=new URLSearchParams({client_id:client.client_id,redirect_uri:redirect,response_type:'code',code_challenge:challenge,code_challenge_method:'S256',resource,scope:scopes,state:'preserved-state'});
 const r=await fetch(base+'/authorize?'+q,{redirect:'manual'});assert.equal(r.status,302);const loc=new URL(r.headers.get('location'));
 const form=await fetch(base+loc.pathname+loc.search);const html=await form.text();const csrf=html.match(/name="csrf" value="([a-f0-9]+)"/)[1];const cookie=form.headers.get('set-cookie').split(';')[0];
 const body=new URLSearchParams({request:loc.searchParams.get('request'),csrf,name,password:'synthetic-test-password-123',create:'yes',approved:'yes'});
 const result=await fetch(base+'/consent',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Cookie:cookie,Origin:origin},body,redirect:'manual'});assert.equal(result.status,302);const callback=new URL(result.headers.get('location'));assert.equal(callback.origin,'https://chatgpt.com');assert.equal(callback.searchParams.get('state'),'preserved-state');return {code:callback.searchParams.get('code'),request:loc.searchParams.get('request'),csrf,cookie,body};
}
async function token(base,client,code,codeVerifier=verifier,requestedResource=resource){return fetch(base+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:client.client_id,code,code_verifier:codeVerifier,redirect_uri:redirect,resource:requestedResource})});}
async function connect(base,token){const c=new Client({name:'authenticated-test',version:'1.0'});const t=new StreamableHTTPClientTransport(new URL(base+'/mcp'),{requestInit:{headers:{Authorization:'Bearer '+token}}});await c.connect(t);return {c,t};}
async function finish(connection){try{await connection.t.terminateSession();}catch{}await connection.c.close();}

test('OAuth Discovery, HTTPS-Konfiguration und kein anonymer Zugriff',async()=>{assert.throws(()=>startReleaseServer({publicOrigin:'http://unsafe.example',port:0}));assert.throws(()=>startReleaseServer({publicOrigin:'https://release.example/path',port:0}));const {app,base}=await setup();try{const as=await (await fetch(base+'/.well-known/oauth-authorization-server')).json();assert.deepEqual(as.code_challenge_methods_supported,['S256']);assert.ok(as.registration_endpoint);const rs=await (await fetch(base+'/.well-known/oauth-protected-resource/mcp')).json();assert.equal(rs.resource,resource);const r=await fetch(base+'/mcp',{method:'POST'});assert.equal(r.status,401);assert.match(r.headers.get('www-authenticate'),/resource_metadata=/);assert.equal((await fetch(base+'/api/tool',{method:'POST'})).status,404);assert.equal((await fetch(base)).headers.get('set-cookie'),null);}finally{await app.close();}});

test('OAuth: echte PKCE-, Resource-, Consent-CSRF- und Code-Replay-Prüfung',async()=>{const {app,base}=await setup();try{const client=await register(base);const auth=await authorization(base,client,'pkce-test');const wrong=await token(base,client,auth.code,'wrong-verifier');assert.equal(wrong.status,400);assert.equal((await wrong.json()).error,'invalid_grant');assert.equal((await token(base,client,auth.code,verifier,'https://other.example/mcp')).status,400);const ok=await token(base,client,auth.code);assert.equal(ok.status,200);assert.ok((await ok.json()).access_token);assert.equal((await token(base,client,auth.code)).status,400);
 const p=new URLSearchParams({client_id:client.client_id,redirect_uri:redirect,response_type:'code',code_challenge:challenge,code_challenge_method:'S256',resource,scope:'loops:read'});const r=await fetch(base+'/authorize?'+p,{redirect:'manual'});const id=new URL(r.headers.get('location')).searchParams.get('request');const denied=await fetch(base+'/consent',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:origin},body:new URLSearchParams({request:id,name:'pkce-test',password:'synthetic-test-password-123',approved:'yes',csrf:'f'.repeat(64)}),redirect:'manual'});assert.equal(denied.status,403);
 const badRedirect=await fetch(base+'/authorize?'+new URLSearchParams({...Object.fromEntries(p),redirect_uri:'https://attacker.example/callback'}),{redirect:'manual'});assert.equal(badRedirect.status,400);
 }finally{await app.close();}});

test('Authentifizierte Tools: Schreibrechte, stabile Kontentrennung und Persistenz nach Neustart',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'dranbleib-auth-')),path=join(dir,'auth.sqlite');let {app,base}=await setup(path);const connections=[];
 try{const ca=await register(base),cb=await register(base);const aa=await authorization(base,ca,'alice-test'),ab=await authorization(base,cb,'bob-test','loops:read');const ta=await (await token(base,ca,aa.code)).json(),tb=await (await token(base,cb,ab.code)).json();const a=await connect(base,ta.access_token),b=await connect(base,tb.access_token);connections.push(a,b);
 const invoke=(c,name,args={})=>c.callTool({name,arguments:args});const tools=(await a.c.listTools()).tools;assert.deepEqual(tools.find(t=>t.name==='capture_open_loop')._meta.securitySchemes,[{type:'oauth2',scopes:['loops:read','loops:write']}]);
 const p=(await invoke(a.c,'preview_open_loop',{text:'Bitte bis Freitag antworten.'})).structuredContent.proposal;const loop=(await invoke(a.c,'capture_open_loop',{proposalId:p.proposalId,fields:p.fields,confirmed:true})).structuredContent.loop;
 assert.equal((await invoke(b.c,'list_open_loops')).structuredContent.loops.length,0);assert.equal((await invoke(b.c,'get_open_loop',{id:loop.id})).isError,true);
 const bp=(await invoke(b.c,'preview_open_loop',{text:'Bitte Testangebot senden.'})).structuredContent.proposal;const noWrite=await invoke(b.c,'capture_open_loop',{proposalId:bp.proposalId,fields:bp.fields,confirmed:true});assert.equal(noWrite.isError,true);assert.ok(noWrite._meta['mcp/www_authenticate']);
 for(const c of connections)await finish(c);connections.length=0;await app.close();({app,base}=await setup(path));const reconnected=await connect(base,ta.access_token);connections.push(reconnected);assert.equal((await invoke(reconnected.c,'list_open_loops')).structuredContent.loops[0].id,loop.id);
 const refresh=await fetch(base+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:ca.client_id,refresh_token:ta.refresh_token,resource})});assert.equal(refresh.status,200);const rotated=await refresh.json();assert.notEqual(rotated.access_token,ta.access_token);assert.equal((await fetch(base+'/mcp',{headers:{Authorization:'Bearer '+ta.access_token}})).status,401);assert.equal((await fetch(base+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:ca.client_id,refresh_token:ta.refresh_token,resource})})).status,400);
  assert.equal((await fetch(base+'/mcp',{headers:{Authorization:'Bearer '+rotated.access_token}})).status,401);
 }finally{for(const c of connections)await finish(c);await app.close();rmSync(dir,{recursive:true,force:true});}
});

test('Konto löschen: CSRF und Passwort erforderlich, Daten und Zugriffe werden widerrufen',async()=>{const {app,base}=await setup();try{const client=await register(base),a=await authorization(base,client,'delete-test'),tokens=await (await token(base,client,a.code)).json();const id=await app.provider.login('delete-test','synthetic-test-password-123');assert.ok(id);const p=app.store.execute(app.provider.owner(id),'preview_open_loop',{text:'Bitte etwas senden.'}).proposal;app.store.execute(app.provider.owner(id),'capture_open_loop',{proposalId:p.proposalId,fields:p.fields,confirmed:true});const f=await fetch(base+'/account/delete');const html=await f.text(),csrf=html.match(/name="csrf" value="([a-f0-9]+)"/)[1],cookie=f.headers.get('set-cookie').split(';')[0];const form=new URLSearchParams({name:'delete-test',password:'synthetic-test-password-123',confirmed:'yes',csrf});assert.equal((await fetch(base+'/account/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:origin},body:form})).status,403);assert.equal((await fetch(base+'/account/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:origin,Cookie:cookie},body:form})).status,200);assert.equal(app.store.list(app.provider.owner(id)).length,0);assert.equal(await app.provider.login('delete-test','synthetic-test-password-123'),null);assert.equal((await fetch(base+'/mcp',{headers:{Authorization:'Bearer '+tokens.access_token}})).status,401);}finally{await app.close();}});
