import { chromium } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { once } from 'node:events';
import { mkdirSync, mkdtempSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
import { startServer } from '../src/server.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
const dir=mkdtempSync(join(tmpdir(),'dranbleib-ui-'));
const app=startServer({port:0,dataPath:join(dir,'test.sqlite')});await once(app.http,'listening');const base=`http://127.0.0.1:${app.http.address().port}`;
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:existsSync('/usr/bin/chromium')?{executablePath:'/usr/bin/chromium'}:{})});
const errors=[];let client,transport,recording;
const filming=process.env.DRANBLEIB_RECORD_VIDEO==='1';
async function pause(){if(filming)await new Promise(r=>setTimeout(r,1200));}
async function untilText(locator,text){await locator.getByText(text,{exact:false}).first().waitFor();}
async function capture(page,title){await page.locator('#source').fill('Könnten Sie uns das aktualisierte Angebot bis Freitag schicken?');await page.getByRole('button',{name:'Vorgang vorschlagen'}).click();await page.locator('#review').waitFor({state:'visible'});assert.match(await page.locator('#evidence').innerText(),/Freitag.*nicht eindeutig/);await page.locator('#review-fields [name=title]').fill(title);await page.locator('#review-fields [name=status]').selectOption('wartend');await page.locator('#review-fields [name=nextAction]').fill('Am Freitag beim Anbieter nachfragen.');await page.locator('#review-fields [name=waitingOn]').fill('Ich warte auf den Anbieter');await page.locator('#review-fields [name=dueDate]').fill('2020-01-01');if(filming)await page.locator('#review-heading').scrollIntoViewIfNeeded();await pause();await page.locator('#approve').check();await page.getByRole('button',{name:'Bestätigen & speichern'}).click();await untilText(page.locator('#loops'),title);await pause();}
try{
 const context=await browser.newContext({viewport:{width:390,height:844},locale:'de-DE',...(filming?{recordVideo:{dir:'artifacts/recordings',size:{width:390,height:844}}}:{})});const page=await context.newPage();if(filming)recording=page.video();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await untilText(page.locator('#loops'),'Hier ist noch Platz');
 await page.locator('#file').setInputFiles({name:'notiz.txt',mimeType:'text/plain',buffer:Buffer.from('Bitte bis 2026-10-09 antworten.')});await page.waitForFunction(()=>document.getElementById('source').value.includes('2026-10-09'));await page.getByRole('button',{name:'Vorgang vorschlagen'}).click();await page.locator('#review').waitFor({state:'visible'});await page.getByRole('button',{name:'Verwerfen',exact:true}).click();assert.equal(await page.locator('#review').isVisible(),false);
 await capture(page,'Angebot nachhalten');await page.getByRole('button',{name:'Überfällig',exact:true}).click();await untilText(page.locator('#loops'),'Angebot nachhalten');
 await page.getByRole('button',{name:'Details & nächster Schritt'}).click();await page.getByRole('button',{name:'Nachfassentwurf',exact:true}).click();await page.locator('#draft-panel').waitFor({state:'visible'});assert.match(await page.locator('#draft').inputValue(),/Angebot nachhalten/);await page.locator('#draft').fill('Mein bearbeiteter Entwurf');await pause();
 await page.locator('#edit-fields [name=dueDate]').fill('2099-10-09');await page.locator('#edit-approve').check();await page.getByRole('button',{name:'Änderungen speichern'}).click();await untilText(page.locator('#loops'),'Keine Vorgänge');await page.getByRole('button',{name:'Wartend',exact:true}).click();await untilText(page.locator('#loops'),'Angebot nachhalten');
 const other=await browser.newContext();const otherPage=await other.newPage();await otherPage.goto(base);await untilText(otherPage.locator('#loops'),'Hier ist noch Platz');assert.ok(!(await otherPage.locator('#loops').innerText()).includes('Angebot nachhalten'));await other.close();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Meine Vorgänge als JSON exportieren'}).click();assert.equal((await download).suggestedFilename(),'dranbleib-export.json');
 await page.reload();await untilText(page.locator('#loops'),'Angebot nachhalten');await page.getByRole('button',{name:'Details & nächster Schritt'}).click();await page.getByRole('button',{name:'Als erledigt markieren'}).click();await page.locator('#confirm-dialog').waitFor({state:'visible'});await pause();await page.locator('#confirm-yes').click();await untilText(page.locator('#loops'),'Angebot nachhalten');await page.getByRole('button',{name:'Erledigt',exact:true}).click();await untilText(page.locator('#loops'),'Angebot nachhalten');
 await page.getByRole('button',{name:'Vorgang löschen',exact:true}).click();await page.locator('#confirm-dialog').waitFor({state:'visible'});await pause();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();assert.equal(await page.locator('.loop').count(),1);
 mkdirSync('artifacts',{recursive:true});await page.screenshot({path:'artifacts/dranbleib-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Kein horizontaler Overflow auf Mobilgeräten');
 await page.getByRole('button',{name:'Vorgang löschen',exact:true}).click();await page.locator('#confirm-yes').click();await untilText(page.locator('#loops'),'Keine Vorgänge');await page.getByRole('button',{name:'Alle',exact:true}).click();await untilText(page.locator('#loops'),'Hier ist noch Platz');
 console.log('PASS Browser: Datei, Vorschlag, Korrektur, Speichern, Filter, Friständerung, Entwurf, Export, Persistenz, Datentrennung, Abschluss, Löschbestätigung, mobile Darstellung.');
 // Simulated MCP Apps host with real MCP tools/resources. This is not a ChatGPT account test.
 client=new Client({name:'ui-host-test',version:'1.0'});transport=new StreamableHTTPClientTransport(new URL(base+'/mcp'));await client.connect(transport);const resource=await client.readResource({uri:'ui://dranbleib/v1.html'});const widget=resource.contents[0].text;
 const host=await context.newPage();host.on('pageerror',e=>errors.push(e.message));await host.exposeFunction('hostRpc',async message=>{if(message.method==='ui/initialize')return {protocolVersion:'2026-01-26',hostInfo:{name:'test-host',version:'1.0'},hostCapabilities:{serverTools:{}}};if(message.method==='tools/call')return client.callTool(message.params);return {};});
 await host.route(base+'/harness',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><iframe title="MCP App" style="width:100%;height:1000px;border:0"></iframe></body></html>'}));await host.goto(base+'/harness');await host.evaluate(widget=>{const frame=document.querySelector('iframe');window.addEventListener('message',async event=>{if(event.source!==frame.contentWindow || event.data?.jsonrpc!=='2.0' || !event.data.id)return;try{const result=await window.hostRpc(event.data);frame.contentWindow.postMessage({jsonrpc:'2.0',id:event.data.id,result},'*');}catch(e){frame.contentWindow.postMessage({jsonrpc:'2.0',id:event.data.id,error:{message:e.message}},'*');}});frame.srcdoc=widget;},widget);
 const frame=host.frameLocator('iframe');await untilText(frame.locator('#loops'),'Hier ist noch Platz');await capture(frame,'MCP Angebot');await frame.getByRole('button',{name:'Details & nächster Schritt'}).click();await frame.getByRole('button',{name:'Antwortentwurf',exact:true}).click();await frame.locator('#draft-panel').waitFor({state:'visible'});assert.match(await frame.locator('#draft').inputValue(),/MCP Angebot/);
 await host.screenshot({path:'artifacts/dranbleib-mcp-host.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));console.log('PASS MCP Apps Host-Simulation: Bridge-Initialisierung, echte MCP-Resource und Tools, Erfassen/Prüfen/Speichern/Entwurf. Keine Browserfehler.');
}finally{if(transport){await transport.terminateSession();await client.close();}await browser.close();if(recording){mkdirSync('assets',{recursive:true});execFileSync('ffmpeg',['-y','-i',await recording.path(),'-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart','assets/walkthrough.mp4'],{stdio:'ignore'});}await app.close();rmSync(dir,{recursive:true,force:true});}
